spring:
  application:
    name: spring-boot-admin-server

server:
  port: 8080
  management:
    endpoint:
      health:
        show-details: always
    endpoints:
      web:
        exposure:
          include: '*'