server:
  port: 8081

spring:
  redis:
    host: 119.23.230.200
    port: 6379
    database: 0

dubbo:
  application:
    name:  dubbo-consumer
  registry:
    address: 119.23.230.200:2181
    # 读者请换成自己的zookeeperip
    protocol: zookeeper
    check: false
  monitor:
    protocol: register
  consumer:
    check:  false
    timeout: 3000